openapi: 3.0.3
info:
  title: Movie API
  description: API for managing movies.
  version: 1.0.0
paths:
  /movie:
    post:
      summary: Create a new movie
      description: Creates a new movie entry.
      operationId: createMovie
      requestBody:
        description: Movie data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Movie'
      responses:
        '201':
          description: Movie created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        '400':
          description: Bad request
          content:
            application/json:
              example:
                error: Bad request
        '500':
          description: Internal server error
          content:
            application/json:
              example:
                error: Internal server error

  openapi: 3.0.3
info:
  title: Movie API
  description: API for managing movies.
  version: 1.0.0
paths:
  /movie/{id}:
    get:
      summary: Get movie details
      description: Retrieves details of a movie by its ID.
      operationId: getMovie
      parameters:
        - name: id
          in: path
          description: ID of the movie to retrieve
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Movie details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        '404':
          description: Movie not found
          content:
            application/json:
              example:
                error: Movie not found
        '500':
          description: Internal server error
          content:
            application/json:
              example:
                error: Internal server error
components:
  schemas:
    Movie:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        director:
          type: string
        release_date:
          type: string
              

                